import { DATE_FORMAT, LANGUAGE, START_WEEK } from "constants/date-time.const";
import { createContext } from "react";

const DatepickerContext = createContext({
  input: undefined,
  primaryColor: "blue",
  configs: undefined,
  calendarContainer: null,
  arrowContainer: null,
  period: { start: null, end: null },
  changePeriod: (period) => {},
  hideDatepicker: () => {},
  dayHover: null,
  changeDayHover: (day) => {},
  inputText: "",
  changeInputText: (text) => {},
  updateFirstDate: (date) => {},
  changeDatepickerValue: (value, e) => {},
  showFooter: false,
  onlyMonthAndYear: true,
  value: null,
  i18n: LANGUAGE,
  disabled: false,
  inputClassName: "",
  containerClassName: "",
  toggleClassName: "",
  readOnly: false,
  displayFormat: DATE_FORMAT,
  minDate: null,
  maxDate: null,
  dateLooking: "forward",
  disabledDates: null,
  inputId: undefined,
  inputName: undefined,
  startWeekOn: START_WEEK,
  toggleIcon: undefined,
  classNames: undefined,
  popoverDirection: undefined,
  separator: "~",
});

export default DatepickerContext;
